# Generated by Django 4.1.12 on 2023-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=50)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('created_time', models.DateTimeField(db_column='created_time')),
                ('updated_time', models.DateTimeField(db_column='updated_time')),
            ],
        ),
    ]
